### PR TITLE
cairo-sys: fix enum types

### LINKED ISSUE #124: Duplicate types of enums in cairo-sys
The following enum types:
```
enums::{
    Antialias,
    Content,
    Extend,
    FillRule,
    LineCap,
    LineJoin,
    Filter,
}
```
have duplicate struct types:
```rust
#[repr(C)]
pub struct cairo_antialias_t(c_void);
#[repr(C)]
pub struct cairo_content_t(c_void);
#[repr(C)]
pub struct cairo_extend_t(c_void);
#[repr(C)]
pub struct cairo_fill_rule_t(c_void);
#[repr(C)]
pub struct cairo_line_cap_t(c_void);
#[repr(C)]
pub struct cairo_line_join_t(c_void);
#[repr(C)]
pub struct cairo_filter_t(c_void);
```
which are unused inside `cairo_sys` repository, but for some reason, seems to be [used](http://gtk-rs.org/docs/gdk_sys/fn.gdk_window_create_similar_surface.html) in other repositories. ([Here](https://github.com/johncf/gtk-scribble-app/blob/master/src/main.rs#L35) is a example usage which does not work.)

### PR DESCRIPTION
**Pull request by johncf**
Fixes #124

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍

**Comment by EPashkin** [comment]
Seems comments about `FontExtents` and `TextExtents` can be removed too.

**Comment by EPashkin** [comment]
.. in cairo-sys-rs/src/lib.rs line 433, 435

**Comment by johncf** [comment]
Should I squash any of those commits?

**Comment by EPashkin** [comment]
Yes, please, and thanks for fixing.
👍

**Comment by johncf** [comment]
It looks like `cairo` has no `Region` implementation yet. So I'll remove `pub use enums::RegionOverlap` from `cairo`.

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
