### PR TITLE
Update Travis/AppVeyor configuration to test/build more different fea…

### PR DESCRIPTION
**Pull request by sdroege**
…tures

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by EPashkin** [comment]
👍

**Comment by GuillaumeGomez** [comment]
```
---- src/pdf.rs - pdf::RefWriter<'w, W>::new (line 261) stdout ----
error[E0433]: failed to resolve: could not find `Stream` in `pdf`
  --> src/pdf.rs:270:20
   |
12 | let surface = pdf::Stream::new(100.0, 100.0, |data|
   |                    ^^^^^^ could not find `Stream` in `pdf`
```

**Comment by sdroege** [comment]
Yeah, the docs stuff here is broken in multiple ways because the CI configuration did not test that. No time to fix that today anymore, maybe tomorrow.

**Comment by GuillaumeGomez** [comment]
I'll do it, don't worry.

**Comment by sdroege** [comment]
Basically there is manual docs in `svg.rs` (and elsewhere) that will cause stuff to fail now, and there's the doctest stuff that also has to enable the features (e.g. `svg` for the stuff in `svg.rs`).

**Comment by sdroege** [comment]
@GuillaumeGomez Erm, can you reopen this again and kick travis? :)

**Comment by GuillaumeGomez** [comment]
Why did it get closed? O.o

**Comment by sdroege** [comment]
Because you closed it in your commit message :)

**Comment by GuillaumeGomez** [comment]
We have some manual docs once again? Let's fix it as well!

**Comment by sdroege** [comment]
You add them to `lgpl-docs` and after that I fix this one here?

**Comment by GuillaumeGomez** [comment]
Yep. Creating the PR in a few minutes.

**Comment by sdroege** [comment]
We have broken code in docs it seems

```rust
---- src/patterns.rs - patterns::Mesh::new (line 444) stdout ----
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `Side`
 --> src/patterns.rs:445:8
  |
3 | C1     Side 1       C2
  |        ^^^^ expected one of 8 possible tokens here
error[E0425]: cannot find value `C1` in this scope
 --> src/patterns.rs:445:1
  |
3 | C1     Side 1       C2
  | ^^ not found in this scope
thread 'src/patterns.rs - patterns::Mesh::new (line 444)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:354:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Requires `v1_12` to happen. Which we maybe should make the default. cairo 1.12 is from 2012 (!).

**Comment by GuillaumeGomez** [comment]
Arf!

**Comment by sdroege** [comment]
Should we make `v1_12` the default or what do you think?

**Comment by GuillaumeGomez** [comment]
Makes sense to me.

**Comment by sdroege** [comment]
Ok, done :)

Now while checking, I also noticed that a) we use 1.12 symbols since quite a while unconditionally anyway so nobody is running with < 1.12, and b) we now also use 1.16 (!) symbols unconditionally.

Someone should go through these lists and put things behind correct feature flags:
https://www.cairographics.org/manual/index-1.14.html
https://www.cairographics.org/manual/index-1.16.html (we use the pdf surface functions since the latest PR)

@GuillaumeGomez can you take care of this or should I put it somewhere on my list?

**Comment by GuillaumeGomez** [comment]
I'll do it, no worries. I'll still open an issue though!

**Comment by GuillaumeGomez** [comment]
Ok all good. The only failure is an OSX worker that didn't start so we can overlook it. Thanks!

**Pull request merged**
