### PR TITLE
Bugfix release

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Any idea what's going on with the CI?

**Comment by EPashkin** [comment]
I can't reproduce it locally, https://github.com/gtk-rs/atk/pull/54 and https://github.com/gtk-rs/pango/pull/179 seems fine too

**Comment by GuillaumeGomez** [comment]
This is... weird.

**Comment by GuillaumeGomez** [comment]
We can't really merge until we figure out what's going on. I'll investigate on linux platforms.

**Comment by sdroege** [comment]
It's the old problem. The examples repo has to be switched to master instead of pending. This is for a stable release. 

Should maybe become part of the release script.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by EPashkin** [comment]
It not in https://github.com/gtk-rs/examples/issues/285  's list, seems I missed this.

**Comment by EPashkin** [comment]
And it also don't have `travis linux stable` for `cargo fmt check`

**Comment by GuillaumeGomez** [comment]
Then I release!

**Comment by sdroege** [comment]
Please don't forget to create tags (did you create tags for glib, gio, gdk, gtk last time?)

**Comment by GuillaumeGomez** [comment]
I created the tag for this one but I didn't for the other crates. :-°

**Comment by sdroege** [comment]
Please do so then :)

**Comment by GuillaumeGomez** [comment]
And done!:

**Pull request merged**
