### PR TITLE
Add an ImageSurface::with_data method.

### LINKED ISSUE #329: Get data out of a referenced ImageSurface
`ImageSurface::get_data` returns an error if the surface is referenced, but I believe it should still be possible to copy the data out safely: since neither `ImageSurface` nor `Context` is `Sync`, there shouldn't be any concurrent modifications.

Of course, there's the question of how to return the data: you can't return `&[u8]`, for reasons discussed in #279. But would you accept a PR to add a method like this?
```rust
impl ImageSurface {
    pub fn copy_data_to(&self, buf: &mut [u8]) -> Result<(), BorrowError>;

    // Or, a more general version
   pub fn with_data<F: FnOnce(&[u8])>(&self, f: F) -> Result<(), BorrowError>;
}
```

### PR DESCRIPTION
**Pull request by jneem**
Fixes #329

### CODE REVIEW

**Comment by jneem** [comment]
So the CI is failing, but I don't understand why. Are API docs not allowed?

**Comment by sdroege** [comment]
Something for the docs expert, @GuillaumeGomez? :)

I think it's complicated and manual docs have to be added to some other file, I'm not sure.

**Comment by GuillaumeGomez** [comment]
Yes, because of license issues we have to store documentation elsewhere and it impacts other documentation too. So please add the doc [here](https://github.com/gtk-rs/lgpl-docs/blob/master/cairo/docs.md) instead.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
