### PR TITLE
Re-submitting matrix methods for Pattern and Context

### PR DESCRIPTION
**Pull request by federicomenaquintero**

### CODE REVIEW

**Comment by EPashkin** [comment]
@federicomenaquintero You don't need recreate Pull request, it updated when your `master` branch

**Comment by EPashkin** [comment]
If you need restart build, just ask @GuillaumeGomez do it.

**Comment by GuillaumeGomez** [comment]
So, for me it's all good. Tests can't pass because of cargo issue so it's not a problem. Since @EPashkin didn't have express problem to fix, I guess it's ok for him as well. Then let's merge! Thanks for your contribution! :)

**Comment by federicomenaquintero** [comment]
Great, thank you!  I'll switch librsvg over to the official repo of gtk-rs/cairo.

**Comment by GuillaumeGomez** [comment]
Great, glad to hear it!

**Pull request merged**
