### PR TITLE
feat(context): add mask_surface method

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1: 

Just waiting for CIs and then I merge, thanks!

**Comment by EPashkin** [comment]
@Brooooooklyn Please try this change
```diff
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,7 +19,7 @@ script:
   - cargo build --features purge-lgpl-docs
   - git diff -R --exit-code
   - mkdir .cargo
-  - echo 'paths = ["."]' > .cargo/config
+  - echo 'paths = [".","./cairo-sys-rs"]' > .cargo/config
   - git clone -q --depth 50 -b pending https://github.com/rust-gnome/examples _examples
   - cd _examples
   - ./build_travis.sh
```

**Comment by Brooooooklyn** [comment]
@EPashkin CI looks good now, thanks

**Comment by EPashkin** [comment]
@Brooooooklyn Thanks for PR
Strange that apveyor not started, but it fails by other reason and need separate fix.

**Pull request merged**
