### PR TITLE
Add more checks

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I found the issue here on osx: the method `ImageSurface::create_from_png`. It fails when leaving the `read_func`. And that's pretty much all we can get at this point... I suppose there is a bug in the osx implementation. We can still make a workaround for osx.

**Comment by EPashkin** [comment]
It not related to #185?

**Comment by GuillaumeGomez** [comment]
Ah maybe?

**Comment by GuillaumeGomez** [comment]
It seems to be working now so I merge (but the issue on OSX and potentially windows remains).

**Pull request merged**
