### PR TITLE
Make winapi optional. (backport into 0.7)

### PR DESCRIPTION
**Pull request by ilya-epifanov**
Cherry-pick of f3ee7e9dcd0b1289ba8ec0cfcd85c6f89b55816b into 0.7

### CODE REVIEW

**Comment by sdroege** [comment]
We don't actively maintain releases before the last stable release. Is there any specific reason you can't upgrade to 0.8?

**Comment by ilya-epifanov** [comment]
I'm using https://github.com/antoyo/relm which is not using 0.8 yet

**Comment by sdroege** [comment]
Ah that's suboptimal. @antoyo anything specifically blocking you from updating relm?

**Comment by antoyo** [comment]
@sdroege: I thought it was already up-to-date, but it's not.
I'll do it soon.

**Comment by sdroege** [comment]
Let's close this one then? @GuillaumeGomez ?

**Pull request closed without merging**
