### PR TITLE
Remove unneeded `mut`

### PR DESCRIPTION
**Pull request by EPashkin**
```
warning: variable does not need to be mutable
  --> D:/eap/rust/0/cairo\src\image_surface_png.rs:36:9
   |
36 |     let mut buffer = slice::from_raw_parts_mut(data, len as usize);
   |         ^^^^^^^^^^
   |
   = note: #[warn(unused_mut)] on by default
```

@GuillaumeGomez Not sure that it pass CI.

### CODE REVIEW

**Comment by EPashkin** [comment]
Strange appveyor failure, no errors but test failed :(

**Comment by EPashkin** [comment]
I tested building 32bit rust on windows 7 64 show messagebox with this text.
```
cargo test -v --no-default-features --features "png"
---------------------------
cairo-e53d705d37bebe62.exe - Точка входа не найдена //Entry point not found
---------------------------
Точка входа в процедуру __divmoddi4 не найдена в библиотеке DLL libgcc_s_dw2-1.dll. 
-------------------------
```
without cairo-e53d705d37bebe62.exe running fine

**Comment by GuillaumeGomez** [comment]
Ah. A change in DLLs then?

**Comment by EPashkin** [comment]
On windows 10 x64 same scenario runs normally.

**Comment by EPashkin** [comment]
Yes,  toolchain bin folder (.rustup/stable-i686-pc-windows-gnu/bin) contains libgcc_s_dw2-1.dll from 2017-03-30 without __divmoddi4
while msys32 bin folder - libgcc_s_dw2-1.dll from 2017-08-15 with it.
Don't fully understand why it used on windows7 but not used on my machine,
but if I rename it in toolchain cargo tests fine

**Comment by EPashkin** [comment]
32bit build "fixed" but I don't like this method, so IMHO better wait.

**Comment by EPashkin** [comment]
@GuillaumeGomez I still not found better solution, so this ready for merge.

**Comment by GuillaumeGomez** [comment]
Ok. Thanks then!

**Pull request merged**
