### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/release/issues/77
cc @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Waiting for CI and then I merge. I'll cherry pick the commits once done.

**Comment by EPashkin** [comment]
I already have branch for master too https://github.com/gtk-rs/cairo/compare/master...EPashkin:warnings?expand=1

**Comment by GuillaumeGomez** [comment]
Oh. No need to worry about it, I'll just cherry-pick the commits like I said.

**Comment by GuillaumeGomez** [comment]
The release can resume now.

**Pull request merged**
