### PR TITLE
Fix dox for non-windows

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gtk/pull/583

cc @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! Just waiting for CIs now.

**Comment by EPashkin** [comment]
Copied change to wrong file :(

**Comment by EPashkin** [comment]
Seems travis need activate "Auto cancel pull request build".

**Comment by GuillaumeGomez** [comment]
It's already activated.

**Comment by EPashkin** [comment]
Then it not works well :(

**Comment by GuillaumeGomez** [comment]
I can't do much about this fact haha.

**Pull request merged**
