### PR TITLE
Refactor interface in PDF

### PR DESCRIPTION
**Pull request by vojtechkral**
Hi,
  this is a follow-up to the discussion in d39b674ef9e7a73cafebf7fa32e4eb7ae82f6900
This PR is not meant to be merged as-is, but as a place to discuss the interface of the additional surfaces (PDF, PS, SVG, ...).

I did the refactoring on PDF so far as an example (the others are analogous I believe).

I tried my best to reconcile the requirements mentioned in the talk under the commit, let me know if I forgot something.
Hopefully none of the changes are too offensive.

Basically there's the basic `File` type, I think that one is unchaged as far as public interface is concerned. Then there's `Writer` and `RefWriter`, the naming is inspired by `Cell` and `RefCell` but is open for bikeshedding - let me know if you prefer different naming. These two additional surface types `Deref` to the `File`. `RefWriter` is basically the same as the former `Writer` and `Writer` is the same thing except taking the ownership of the `io::Write` thing passed in.

In the end I decided to leave the `W: io::Write` type as part of the `Writer` and `RefWriter` types, this allows for single boxing and no boxing respectively and also allows to get the `W` back from the `Writer` using `finish()`.

Please see the tests to get a feeling of how the interface is used.

cc @meh @sdroege

### CODE REVIEW

**Comment by sdroege** [comment]
@meh please also review this :)

**Comment by sdroege** [comment]
> Also we should remember to remove the old `pdf_surface.rs` slightly_smiling_face

Can you add a commit to this PR, doing exactly that?

**Comment by sdroege** [comment]
It would also be good to summarize in the commit message what the goal of this refactoring is (what it should enable, for example) and what the exact changes are :) I didn't follow the old discussion closely so the changes don't tell me much as is currently.

**Comment by vojtechkral** [comment]
@sdroege Sure, I added and explanation to the commit message, hope it makes sense. Also added the commit removing `pdf_surface.rs`. For me the most important differences are:

- I can move an `io::Write` into a surface (rather than reference it with a lifetime) and get it back once drawing is done (this was sort-of possible with the old interface as well but required boilerplate / wasn't straightforward)
- We can add more function bindings to the surface in a normal way without having to add them to 4 distinct types via a macro or something

**Comment by meh** [comment]
I need to look more carefully at this next week, have some concerns about stuff related to writing to a buffer, can someone ping me on Hangouts or IRC next week if I forget please?

**Comment by GuillaumeGomez** [comment]
@meh you forgot

**Comment by GuillaumeGomez** [comment]
@meh No release until you review this!

**Comment by meh** [comment]
Okay, I don't mind the changes wrt. `Buffer`, the stuff I have still works with this refactor, with minor changes.

**Comment by GuillaumeGomez** [comment]
Since @meh agrees, let's merge. Thanks @vojtechkral !

**Comment by vojtechkral** [comment]
@meh I hope I didn't mess up anything for you :) Thank you for looking into this.

@GuillaumeGomez I didn't mean for this to be merged directly, but I guess it's ok if everyone else is ok with it. In any case, I should follow up with equal refacroring in PS & SVG and write docs. I will look into that sometimes in the next couple of days. Thank you as well.

**Comment by sdroege** [comment]
@GuillaumeGomez yeah this was merged before it was actually finished :) Now we have to either wait for it to be finished or revert it before the release, I guess.

**Comment by GuillaumeGomez** [comment]
Damn, I was sure it was done. Well, let's wait. :-.

**Comment by vojtechkral** [comment]
I'll speed it up. Got SVG done on train today, will do the rest later on...

**Comment by GuillaumeGomez** [comment]
Awesome!

**Comment by vojtechkral** [comment]
#236

**Pull request merged**
