### PR TITLE
Fix dox feature

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
Yes, it some solution, but docs will link `Display` or others to local version :(
And `surface.rs` also need add two `feature = "dox"` to remove errors.
IMHO better wait for normal fix, maybe fixed x11 will published today.

**Comment by GuillaumeGomez** [comment]
Let's wait then.

**Comment by GuillaumeGomez** [comment]
Ok, updated this one. Thanks for the fix in the x11 crate! :)

**Comment by GuillaumeGomez** [comment]
@EPashkin: Do you have a 32 bits windows by any chance? I wonder if it's a rustc bug...

**Comment by EPashkin** [comment]
No :(

**Comment by GuillaumeGomez** [comment]
Arf... I have no idea where I could such a thing... I mean a 32 bits windows XD. I'll go around and check for old computers.

**Comment by GuillaumeGomez** [comment]
Ok, I have nothing like an old 32 bits computer around me. I'll try find something further but for now, let's just merge this one...

**Pull request merged**
