### PR TITLE
deps: don't restrict c_vec version

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Why would we not want to restrict the `c_vec` version?

**Comment by ignatenkobrain** [comment]
@GuillaumeGomez I think question is rather opposite, why would you? c_vec is not known (to my knowlecge) by breaking API between minor versions.

**Comment by GuillaumeGomez** [comment]
Well, I have to admit that I don't care enough about it to start a debate so let's say it's ok for me. 😆 

@EPashkin: Any reason we shouldn't merge this PR? Otherwise I'm just gonna merge.

**Comment by EPashkin** [comment]
IMHO restricting really unneeded, It was done for version 1.0, and just upgraded since.

**Comment by GuillaumeGomez** [comment]
Then I merge.

Thanks @ignatenkobrain!

**Pull request merged**
