### PR TITLE
Add missing types and version features

### LINKED ISSUE #239: 1.14 and 1.16 versions aren't handled correctly

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #239.

cc @sdroege @EPashkin

### CODE REVIEW

**Comment by sdroege** [comment]
Looks good to me, but you also added some new functions that we didn't have before and the commit message does not mention that :) You didn't add all new functions though, only some (and there are also many from 1.12 that we are still missing IIRC).

**Comment by GuillaumeGomez** [comment]
I added all 1.14 and 1.16 functions/constants. I can add the 1.12 stuff as well. I'll do it in another PR though. I'll merge this one for the moment.

**Comment by sdroege** [comment]
>  I can add the 1.12 stuff as well. I'll do it in another PR though. I'll merge this one for the moment.

Sure, not urgent. If someone needs it someone will ask for it :)

**Comment by GuillaumeGomez** [comment]
Too late, already implementing everything missing.

**Pull request merged**
