### PR TITLE
Error trait for errors

### LINKED ISSUE #137: Implement Error trait for IoError
So it can be used with `derive-error`/`error-chain`.

### PR DESCRIPTION
**Pull request by EPashkin**
Closes #137

Also removed unused warning for non "macos" system.

cc @GuillaumeGomez, @sdroege  , @RazrFalcon

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
CI passed and seems good to me. Unless you prefer to wait for someone else's review?

**Comment by EPashkin** [comment]
IMHO better at minimum wait for @RazrFalcon.

**Comment by GuillaumeGomez** [comment]
Fine by me. :)

**Comment by sdroege** [comment]
:+1:

**Comment by RazrFalcon** [comment]
Looks good. Thanks.

**Pull request merged**
