### PR TITLE
Make Surface methods &self from &mut self, remove Send impls

### LINKED ISSUE #232: Shouldn't ImageSurface has an AsMut<Surface> impl?
Currently I can get a `&Surface` from a `&ImageSurface`, but I can't get a `&mut Surface` from `&mut ImageSurface` because there isn't an impl `AsMut<Surface> for ImageSurface`. This makes some operations impossible, e.g. I can't call `set_device_offset()` (added with #230) on an `ImageSurface`.

### PR DESCRIPTION
**Pull request by osa1**
Fixes #232

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
Still looks good to me :)

**Comment by sdroege** [comment]
@GuillaumeGomez This of course breaks the example that makes use of the `Send` impl on the image surface but that example should be rewritten IMHO anyway, it's quite ugly :) I can make it work again without rewriting it all though, once this is merged here.

**Comment by GuillaumeGomez** [comment]
Ok, then I'll just merge and wait for your example rewrite. :)

Thanks @osa1 !

**Comment by sdroege** [comment]
> Ok, then I'll just merge and wait for your example rewrite. :)

Can you create an issue for that and CC me there so I don't forget?

**Comment by GuillaumeGomez** [comment]
Sure.

**Pull request merged**
