### PR TITLE
Reexport the Gradient type too.

### LINKED ISSUE #272: Shouldn't the Gradient type be reexported?
[This code](https://github.com/gtk-rs/cairo/blob/3bd65dad0c45fa2976684de9285492679895c9cc/src/lib.rs#L84) reexport all pattern types except Gradient. Is it missing or this is intentional?

### PR DESCRIPTION
**Pull request by RazrFalcon**
Closes #272

### CODE REVIEW

**Comment by sdroege** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by sdroege** [comment]
@GuillaumeGomez This should get a bugfix release (with only this single change)

**Comment by GuillaumeGomez** [comment]
Indeed. I'll do that once merged.

**Comment by sdroege** [comment]
@GuillaumeGomez All green :)

**Comment by GuillaumeGomez** [comment]
Then I merge. Please someone ping me tomorrow so I make the minor release.

**Comment by Eijebong** [comment]
@GuillaumeGomez You forgot about this :p

**Pull request merged**
