### PR TITLE
Expose include dirs to other build scripts

### PR DESCRIPTION
**Pull request by kornelski**
Same as https://github.com/gtk-rs/sys/pull/123

### CODE REVIEW

**Comment by kornelski** [comment]
https://github.com/gtk-rs/gir/pull/678

**Comment by sdroege** [comment]
Yes, please reopen :) :+1: for this change

**Comment by kornelski** [comment]
ok

**Comment by EPashkin** [comment]
👍

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
