### PR TITLE
Update crates version

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by EPashkin** [comment]
Don't see changes in sys toml

**Comment by GuillaumeGomez** [comment]
Ah damn, I'll update my script.

**Comment by EPashkin** [comment]
All other seems good

**Comment by GuillaumeGomez** [comment]
Then I'll start the publications. Thanks @EPashkin!

**Comment by EPashkin** [comment]
@GuillaumeGomez 
May be better just push your `GuillaumeGomez:crate` to `gtk-rs/cairo`.
As build fails always and I tracing your fork IMHO only need PR in gtk-rs about publishing new version.

**Comment by GuillaumeGomez** [comment]
I prefer to keep both branches separated. It's not a problem if the build fails.

**Pull request merged**
