### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
You don't want to see if other issues come up before changing version?

**Comment by gkoz** [comment]
I don't mean to release the crates, it's basically the same as https://github.com/gtk-rs/gtk/pull/229 to avoid the impression that master is the same version as on crates.

**Comment by GuillaumeGomez** [comment]
Then all new builds will fail. How do you want to avoid that?

**Comment by gkoz** [comment]
The last time we merged all bumps at the same time and then the builds became compatible once again.

**Comment by GuillaumeGomez** [comment]
Then let's do it again! Thanks @gkoz!

**Pull request merged**
