### PR TITLE
Add lgpl-docs features and minor cleanups

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I can't merge it. Please update it.

**Comment by GuillaumeGomez** [comment]
Also, can you squash the last commit?

**Comment by gkoz** [comment]
It feels wrong to do that: they change separate entities; adjusting CI is not a part of adding those features.

**Comment by GuillaumeGomez** [comment]
From my point of view, it's the same change. The first make the second mandatory.

**Comment by gkoz** [comment]
Perhaps the CI commits should be phrased better. They certainly depend on the presence of the features but the point is quite different: preventing accidental checkins of embedded docs and secondarily detecting doctests breakage.

**Comment by GuillaumeGomez** [comment]
I won't bother with you on this detail furthermore. I don't agree on your arguments but let's merge it. Great work! Thanks! :)

**Pull request merged**
