### PR TITLE
Apveyor: Update pacman DB before installing gtk

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Ah perfect, thanks!

**Comment by EPashkin** [comment]
I think that updating Pacman DB is temporary solution, and better removed when apveyor image get `cairo 1.15.12` by default.

**Comment by EPashkin** [comment]
Just note: while travis for #184 was good, merging have error https://travis-ci.org/gtk-rs/cairo/jobs/366794153#L707, bad if this random error.

**Comment by EPashkin** [comment]
All CI passed here

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
