### PR TITLE
Add quartz functions

### LINKED ISSUE #114: Add Quartz functions
https://www.cairographics.org/manual/cairo-Quartz-Surfaces.html

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #114.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@EPashkin: The build failed locally:

```
> cargo build
   Compiling c_vec v1.2.0
   Compiling libc v0.2.20
   Compiling cairo-rs v0.1.1 (file:///Users/imperio/rust/cairo)
   Compiling bitflags v0.4.0
   Compiling pkg-config v0.3.9
   Compiling bitflags v0.5.0
   Compiling glib-sys v0.3.2 (https://github.com/gtk-rs/sys#11c911ef)
   Compiling gobject-sys v0.3.2 (https://github.com/gtk-rs/sys#11c911ef)
   Compiling cairo-sys-rs v0.3.2 (file:///Users/imperio/rust/cairo/cairo-sys-rs)
   Compiling glib v0.1.1 (https://github.com/gtk-rs/glib#91f2ceb4)
error[E0405]: cannot find trait `FromGlibPtrNone` in this scope
  --> src/context.rs:53:6
   |
53 | impl FromGlibPtrNone<*mut ffi::cairo_t> for Context {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrFull` in this scope
  --> src/context.rs:62:6
   |
62 | impl FromGlibPtrFull<*mut ffi::cairo_t> for Context {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrNone` in this scope
  --> src/image_surface.rs:96:6
   |
96 | impl FromGlibPtrNone<*mut ffi::cairo_surface_t> for ImageSurface {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrFull` in this scope
   --> src/image_surface.rs:103:6
    |
103 | impl FromGlibPtrFull<*mut ffi::cairo_surface_t> for ImageSurface {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrNone` in this scope
  --> src/rectangle.rs:45:6
   |
45 | impl FromGlibPtrNone<*const ffi::cairo_rectangle_int_t> for RectangleInt {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrNone` in this scope
  --> src/rectangle.rs:52:6
   |
52 | impl FromGlibPtrNone<*mut ffi::cairo_rectangle_int_t> for RectangleInt {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrNone` in this scope
  --> src/surface.rs:53:6
   |
53 | impl FromGlibPtrNone<*mut ffi::cairo_surface_t> for Surface {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error[E0405]: cannot find trait `FromGlibPtrFull` in this scope
  --> src/surface.rs:62:6
   |
62 | impl FromGlibPtrFull<*mut ffi::cairo_surface_t> for Surface {
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `FromGlibPtr`?

error: cannot continue compilation due to previous error

error: Could not compile `cairo-rs`.
```

Any idea?

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/glib#91f2ceb4 is too old
delete lock?

**Comment by GuillaumeGomez** [comment]
Ok, passed locally. However, there is a strange failure on nightly...

**Comment by EPashkin** [comment]
Cargo failure issue https://github.com/rust-lang/cargo/issues/3819

**Comment by GuillaumeGomez** [comment]
Cargo once again...

**Comment by GuillaumeGomez** [comment]
@EPashkin: Does the code seem ok to you by the way?

**Comment by EPashkin** [comment]
Yes, code seems right.
About cargo: interesting comment https://github.com/rust-lang/cargo/issues/3819#issuecomment-285954744 Maybe these failures don't repeated after check fixed.

**Comment by GuillaumeGomez** [comment]
Should I merge then?

**Comment by EPashkin** [comment]
IMHO yes

**Comment by GuillaumeGomez** [comment]
Thanks for the review! ;)

**Pull request merged**
