### PR TITLE
Add the high-level RectangleInt struct

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks.

**Comment by GuillaumeGomez** [comment]
It broke tests. Merge anyway?

**Comment by EPashkin** [comment]
Yes, and restart https://github.com/gtk-rs/cairo/pull/76 after merge plz

**Comment by GuillaumeGomez** [comment]
#76?

**Comment by EPashkin** [comment]
https://github.com/gtk-rs/gdk/pull/117

**Pull request merged**
